### ISSUE TITLE
support for real-time collaborative writing of Latex documents?

### ISSUE THREAD

**Issue by monperrus** [jdleesmiller/jotgit#17]
Real-time collaborative writing of Latex documents is heavily used in scientific writing. Today, this niche is dominated by Overleaf.

To what extent is JotGit a valid option to do real-time collaborative writing of Latex documents?

**Comment by jdleesmiller** [comment]
Thanks for getting in touch.

JotGit was a prototype I wrote at Overleaf (of which I'm a cofounder) to explore how real time collaborative editing worked with git. We took the learnings and built them into our git integrations (the 'git bridge' https://github.com/overleaf/writelatex-git-bridge and now direct GitHub sync).

So, jotgit certainly is not ready for prime time --- it was just a prototype.

**Comment by monperrus** [comment]
> JotGit was a prototype I wrote at Overleaf (of which I'm a cofounder)

Small world :-) Thanks a lot for your answer!
